
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QPushButton, QGroupBox, QComboBox, QLineEdit, QScrollBar
from PyQt5 import uic
import sys
import psycopg2
from sqlalchemy import create_engine, MetaData, Table, insert
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.ext.automap import automap_base
import os
from dotenv import load_dotenv
from utilities import teams

load_dotenv()

Base = declarative_base()
engine = create_engine(os.getenv("CONNECTION_STRING"))
metadata = MetaData()
metadata.reflect(bind=engine)
games = Table('picks', metadata, autoload_with=engine)
Session = sessionmaker(bind=engine)

class UI(QMainWindow):
    def __init__(self):
        super(UI, self).__init__()
        
        
        # load the ui file
        uic.loadUi("nfl_picks.ui", self)
        self.setWindowTitle("NFL Picks")
        self.setFixedWidth(950)
        
        
        # Geometry
        #   slate visible: main(50, 50, 850, 910), test(580, 824, 75, 23)
        #                  submit(480, 824, 70, 25), year(300, 824, 70, 25), week(390, 824, 70, 25)
        #   slate hidden:  main(50, 50, 850, 500), test(580, 450, 75, 23)
        #                  submit(480, 450, 70, 25), year(300, 450, 70, 25), week(390, 450, 70, 25)
        
       
        
        # *********************************** WIDGETS *************************************
        # buttons
        self.submit = self.findChild(QPushButton, "submitButton")
        # HIDE THIS TEST BUTTON
        self.toggle = self.findChild(QPushButton, "toggleGroup")
        # HIDE THIS TEST BUTTON
        self.toggleText = self.findChild(QPushButton, "toggleText")
        
        # combo boxes
        self.year = self.findChild(QComboBox, "year")
        self.week = self.findChild(QComboBox, "week")
        
        # group box
        self.slate = self.findChild(QGroupBox, "slate")
        
        # group box widgets
        # day labels
        self.day0 = self.findChild(QLabel,"day0")
        self.day1 = self.findChild(QLabel,"day1")
        self.day2 = self.findChild(QLabel,"day2")
        self.day3 = self.findChild(QLabel,"day3")
        self.day4 = self.findChild(QLabel,"day4")
        self.day5 = self.findChild(QLabel,"day5")
        self.day6 = self.findChild(QLabel,"day6")
        self.day7 = self.findChild(QLabel,"day7")
        self.day8 = self.findChild(QLabel,"day8")
        self.day9 = self.findChild(QLabel,"day9")
        self.day10 = self.findChild(QLabel,"day10")
        self.day11 = self.findChild(QLabel,"day11")
        self.day12 = self.findChild(QLabel,"day12")
        self.day13 = self.findChild(QLabel,"day13")
        self.day14 = self.findChild(QLabel,"day14")
        self.day15 = self.findChild(QLabel,"day15")
        self.day16 = self.findChild(QLabel,"day16")
        self.day17 = self.findChild(QLabel,"day17")
        self.day18 = self.findChild(QLabel,"day18")
        self.day19 = self.findChild(QLabel,"day19")
        
        # OT labels
        self.ot0 = self.findChild(QLabel, "ot0")
        self.ot1 = self.findChild(QLabel, "ot1")
        self.ot2 = self.findChild(QLabel, "ot2")
        self.ot3 = self.findChild(QLabel, "ot3")
        self.ot4 = self.findChild(QLabel, "ot4")
        self.ot5 = self.findChild(QLabel, "ot5")
        self.ot6 = self.findChild(QLabel, "ot6")
        self.ot7 = self.findChild(QLabel, "ot7")
        self.ot8 = self.findChild(QLabel, "ot8")
        self.ot9 = self.findChild(QLabel, "ot9")
        self.ot10 = self.findChild(QLabel, "ot10")
        self.ot11 = self.findChild(QLabel, "ot11")
        self.ot12 = self.findChild(QLabel, "ot12")
        self.ot13 = self.findChild(QLabel, "ot13")
        self.ot14 = self.findChild(QLabel, "ot14")
        self.ot15 = self.findChild(QLabel, "ot15")
        self.ot16 = self.findChild(QLabel, "ot16")
        self.ot17 = self.findChild(QLabel, "ot17")
        self.ot18 = self.findChild(QLabel, "ot18")
        self.ot19 = self.findChild(QLabel, "ot19")
        
        # pick result labels
        self.result0 = self.findChild(QLabel, "result0")
        self.result1 = self.findChild(QLabel, "result1")
        self.result2 = self.findChild(QLabel, "result2")
        self.result3 = self.findChild(QLabel, "result3")
        self.result4 = self.findChild(QLabel, "result4")
        self.result5 = self.findChild(QLabel, "result5")
        self.result6 = self.findChild(QLabel, "result6")
        self.result7 = self.findChild(QLabel, "result7")
        self.result8 = self.findChild(QLabel, "result8")
        self.result9 = self.findChild(QLabel, "result9")
        self.result10 = self.findChild(QLabel, "result10")
        self.result11 = self.findChild(QLabel, "result11")
        self.result12 = self.findChild(QLabel, "result12")
        self.result13 = self.findChild(QLabel, "result13")
        self.result14 = self.findChild(QLabel, "result14")
        self.result15 = self.findChild(QLabel, "result15")
        self.result16 = self.findChild(QLabel, "result16")
        self.result17 = self.findChild(QLabel, "result17")
        self.result18 = self.findChild(QLabel, "result18")
        self.result19 = self.findChild(QLabel, "result19")
        
        # away team labels
        self.away0 = self.findChild(QLabel, "away0")
        self.away1 = self.findChild(QLabel, "away1")
        self.away2 = self.findChild(QLabel, "away2")
        self.away3 = self.findChild(QLabel, "away3")
        self.away4 = self.findChild(QLabel, "away4")
        self.away5 = self.findChild(QLabel, "away5")
        self.away6 = self.findChild(QLabel, "away6")
        self.away7 = self.findChild(QLabel, "away7")
        self.away8 = self.findChild(QLabel, "away8")
        self.away9 = self.findChild(QLabel, "away9")
        self.away10 = self.findChild(QLabel, "away10")
        self.away11 = self.findChild(QLabel, "away11")
        self.away12 = self.findChild(QLabel, "away12")
        self.away13 = self.findChild(QLabel, "away13")
        self.away14 = self.findChild(QLabel, "away14")
        self.away15 = self.findChild(QLabel, "away15")
        self.away16 = self.findChild(QLabel, "away16")
        self.away17 = self.findChild(QLabel, "away17")
        self.away18 = self.findChild(QLabel, "away18")
        self.away19 = self.findChild(QLabel, "away19")
        
        # home team labels
        self.home0 = self.findChild(QLabel, "home0")
        self.home1 = self.findChild(QLabel, "home1")
        self.home2 = self.findChild(QLabel, "home2")
        self.home3 = self.findChild(QLabel, "home3")
        self.home4 = self.findChild(QLabel, "home4")
        self.home5 = self.findChild(QLabel, "home5")
        self.home6 = self.findChild(QLabel, "home6")
        self.home7 = self.findChild(QLabel, "home7")
        self.home8 = self.findChild(QLabel, "home8")
        self.home9 = self.findChild(QLabel, "home9")
        self.home10 = self.findChild(QLabel, "home10")
        self.home11 = self.findChild(QLabel, "home11")
        self.home12 = self.findChild(QLabel, "home12")
        self.home13 = self.findChild(QLabel, "home13")
        self.home14 = self.findChild(QLabel, "home14")
        self.home15 = self.findChild(QLabel, "home15")
        self.home16 = self.findChild(QLabel, "home16")
        self.home17 = self.findChild(QLabel, "home17")
        self.home18 = self.findChild(QLabel, "home18")
        self.home19 = self.findChild(QLabel, "home19")
        
        # away score line edit boxes
        self.aScore0 = self.findChild(QLineEdit, "aScore0")
        self.aScore1 = self.findChild(QLineEdit, "aScore1")
        self.aScore2 = self.findChild(QLineEdit, "aScore2")
        self.aScore3 = self.findChild(QLineEdit, "aScore3")
        self.aScore4 = self.findChild(QLineEdit, "aScore4")
        self.aScore5 = self.findChild(QLineEdit, "aScore5")
        self.aScore6 = self.findChild(QLineEdit, "aScore6")
        self.aScore7 = self.findChild(QLineEdit, "aScore7")
        self.aScore8 = self.findChild(QLineEdit, "aScore8")
        self.aScore9 = self.findChild(QLineEdit, "aScore9")
        self.aScore10 = self.findChild(QLineEdit, "aScore10")
        self.aScore11 = self.findChild(QLineEdit, "aScore11")
        self.aScore12 = self.findChild(QLineEdit, "aScore12")
        self.aScore13 = self.findChild(QLineEdit, "aScore13")
        self.aScore14 = self.findChild(QLineEdit, "aScore14")
        self.aScore15 = self.findChild(QLineEdit, "aScore15")
        self.aScore16 = self.findChild(QLineEdit, "aScore16")
        self.aScore17 = self.findChild(QLineEdit, "aScore17")
        self.aScore18 = self.findChild(QLineEdit, "aScore18")
        self.aScore19 = self.findChild(QLineEdit, "aScore19")
        
        # home score line edit boxes
        self.hScore0 = self.findChild(QLineEdit, "hScore0")
        self.hScore1 = self.findChild(QLineEdit, "hScore1")
        self.hScore2 = self.findChild(QLineEdit, "hScore2")
        self.hScore3 = self.findChild(QLineEdit, "hScore3")
        self.hScore4 = self.findChild(QLineEdit, "hScore4")
        self.hScore5 = self.findChild(QLineEdit, "hScore5")
        self.hScore6 = self.findChild(QLineEdit, "hScore6")
        self.hScore7 = self.findChild(QLineEdit, "hScore7")
        self.hScore8 = self.findChild(QLineEdit, "hScore8")
        self.hScore9 = self.findChild(QLineEdit, "hScore9")
        self.hScore10 = self.findChild(QLineEdit, "hScore10")
        self.hScore11 = self.findChild(QLineEdit, "hScore11")
        self.hScore12 = self.findChild(QLineEdit, "hScore12")
        self.hScore13 = self.findChild(QLineEdit, "hScore13")
        self.hScore14 = self.findChild(QLineEdit, "hScore14")
        self.hScore15 = self.findChild(QLineEdit, "hScore15")
        self.hScore16 = self.findChild(QLineEdit, "hScore16")
        self.hScore17 = self.findChild(QLineEdit, "hScore17")
        self.hScore18 = self.findChild(QLineEdit, "hScore18")
        self.hScore19 = self.findChild(QLineEdit, "hScore19")
        # *********************************** END WIDGETS *************************************
        
        # ACTIONS
        # populate dropdowns
        self.year.addItems([str(year) for year in range(2021, 2025)])
        self.week.addItems([str(week) for week in range(1,19)] + ['WC', 'DIV', 'CONF', 'SB'])
        # hide weekly schedule
        self.slate.setVisible(False)
        self.setPosition(0)
        # attach click functions
        self.toggle.clicked.connect(self.changeGroupVisibility)
        self.toggleText.clicked.connect(self.testText)
        self.submit.clicked.connect(self.getSlate)
        
        
        
        # show the app
        self.show()
        
    def changeGroupVisibility(self):
        if self.slate.isVisible():
            # self.setGeometry(50, 50, 850, 500)
            # self.toggle.setGeometry(580, 450, 75, 23)
            self.setPosition(0)
            self.slate.setVisible(False)
        else:
            # self.setGeometry(50, 50, 850, 910)
            # self.toggle.setGeometry(580, 824, 75, 23)
            self.setPosition(1)
            self.slate.setVisible(True)
            
    def testText(self):
        if self.aScore0.isVisible():
            self.resetSlate()
        else:
            self.showAllText()
        
    def getSlate(self):
        
        self.resetSlate()
        
        week = self.week.currentText()
        year = self.year.currentText()
        title = f"{year} - week {week}"
        self.slate.setTitle(title)
        
        row = 0
        space = 0
        session = Session()
        slate = session.query(games).where(games.columns.season == year).where(games.columns.week == week)
        
        for game in slate:
            day = game[6]
            if row == 0:
                self.day0.setText(game[6][:3])
                self.away0.setText(teams[game[8]])
                self.aScore0.setVisible(True)
                self.aScore0.setText(str(game[9]))
                self.home0.setText(teams[game[10]])
                self.hScore0.setVisible(True)
                self.hScore0.setText(str(game[11]))
                if game[13] == 1:
                    self.ot0.setText("OT")
                if game[17] == 'h':
                    self.home0.setStyleSheet("font-weight: bold")
                    self.result0.setText("C" if game[11] > game[9] else "X")
                elif game[17] == 'a':
                    self.away0.setStyleSheet("font-weight: bold")
                    self.result0.setText("C" if game[9] > game[11] else "X")
            else:
                pass
        
        
        
        
        
        
    def setPosition(self, size):
        if size == 0:
            # small window
            self.setGeometry(self.x()+1, self.y()+31, 950, 500)   # self.setGeometry(self.x(), self.y(), 850, 500)
            #print('x = ', self.x())
            #print ('y = ',self.y())
            # self.toggle.setGeometry(580, 450, 75, 23)
            # self.submit.setGeometry(480, 450, 70, 25)
            # self.year.setGeometry(300, 450, 70, 25)
            # self.week.setGeometry(390, 450, 70, 25)
        else:
            # large window
            self.setGeometry(self.x()+1, self.y()+31, 950, 900)   # self.setGeometry(self.x(), self.y(), 850, 910)
            #print('x = ', self.x())
            #print ('y = ',self.y())
            # self.toggle.setGeometry(580, 824, 75, 23)
            # self.submit.setGeometry(480, 824, 70, 25)
            # self.year.setGeometry(300, 824, 70, 25)
            # self.week.setGeometry(390, 824, 70, 25)
        
    # clear the form
    def resetSlate(self):
        self.aScore0.setText('')
        self.aScore1.setText('')
        self.aScore2.setText('')
        self.aScore3.setText('')
        self.aScore4.setText('')
        self.aScore5.setText('')
        self.aScore6.setText('')
        self.aScore7.setText('')
        self.aScore8.setText('')
        self.aScore9.setText('')
        self.aScore10.setText('')
        self.aScore11.setText('')
        self.aScore12.setText('')
        self.aScore13.setText('')
        self.aScore14.setText('')
        self.aScore15.setText('')
        self.aScore16.setText('')
        self.aScore17.setText('')
        self.aScore18.setText('')
        self.aScore19.setText('')
        
        self.hScore0.setText('')
        self.hScore1.setText('')
        self.hScore2.setText('')
        self.hScore3.setText('')
        self.hScore4.setText('')
        self.hScore5.setText('')
        self.hScore6.setText('')
        self.hScore7.setText('')
        self.hScore8.setText('')
        self.hScore9.setText('')
        self.hScore10.setText('')
        self.hScore11.setText('')
        self.hScore12.setText('')
        self.hScore13.setText('')
        self.hScore14.setText('')
        self.hScore15.setText('')
        self.hScore16.setText('')
        self.hScore17.setText('')
        self.hScore18.setText('')
        self.hScore19.setText('')
        
        self.aScore0.setVisible(False)
        self.aScore1.setVisible(False)
        self.aScore2.setVisible(False)
        self.aScore3.setVisible(False)
        self.aScore4.setVisible(False)
        self.aScore5.setVisible(False)
        self.aScore6.setVisible(False)
        self.aScore7.setVisible(False)
        self.aScore8.setVisible(False)
        self.aScore9.setVisible(False)
        self.aScore10.setVisible(False)
        self.aScore11.setVisible(False)
        self.aScore12.setVisible(False)
        self.aScore13.setVisible(False)
        self.aScore14.setVisible(False)
        self.aScore15.setVisible(False)
        self.aScore16.setVisible(False)
        self.aScore17.setVisible(False)
        self.aScore18.setVisible(False)
        self.aScore19.setVisible(False)
        
        self.hScore0.setVisible(False)
        self.hScore1.setVisible(False)
        self.hScore2.setVisible(False)
        self.hScore3.setVisible(False)
        self.hScore4.setVisible(False)
        self.hScore5.setVisible(False)
        self.hScore6.setVisible(False)
        self.hScore7.setVisible(False)
        self.hScore8.setVisible(False)
        self.hScore9.setVisible(False)
        self.hScore10.setVisible(False)
        self.hScore11.setVisible(False)
        self.hScore12.setVisible(False)
        self.hScore13.setVisible(False)
        self.hScore14.setVisible(False)
        self.hScore15.setVisible(False)
        self.hScore16.setVisible(False)
        self.hScore17.setVisible(False)
        self.hScore18.setVisible(False)
        self.hScore19.setVisible(False)
        
        self.day0.setText('')
        self.day1.setText('')
        self.day2.setText('')
        self.day3.setText('')
        self.day4.setText('')
        self.day5.setText('')
        self.day6.setText('')
        self.day7.setText('')
        self.day8.setText('')
        self.day9.setText('')
        self.day10.setText('')
        self.day11.setText('')
        self.day12.setText('')
        self.day13.setText('')
        self.day14.setText('')
        self.day15.setText('')
        self.day16.setText('')
        self.day17.setText('')
        self.day18.setText('')
        self.day19.setText('')
        
        self.ot0.setText('')
        self.ot1.setText('')
        self.ot2.setText('')
        self.ot3.setText('')
        self.ot4.setText('')
        self.ot5.setText('')
        self.ot6.setText('')
        self.ot7.setText('')
        self.ot8.setText('')
        self.ot9.setText('')
        self.ot10.setText('')
        self.ot11.setText('')
        self.ot12.setText('')
        self.ot13.setText('')
        self.ot14.setText('')
        self.ot15.setText('')
        self.ot16.setText('')
        self.ot17.setText('')
        self.ot18.setText('')
        self.ot19.setText('')
        
        self.result0.setText('')
        self.result1.setText('')
        self.result2.setText('')
        self.result3.setText('')
        self.result4.setText('')
        self.result5.setText('')
        self.result6.setText('')
        self.result7.setText('')
        self.result8.setText('')
        self.result9.setText('')
        self.result10.setText('')
        self.result11.setText('')
        self.result12.setText('')
        self.result13.setText('')
        self.result14.setText('')
        self.result15.setText('')
        self.result16.setText('')
        self.result17.setText('')
        self.result18.setText('')
        self.result19.setText('')
        
        self.away0.setText('')
        self.away1.setText('')
        self.away2.setText('')
        self.away3.setText('')
        self.away4.setText('')
        self.away5.setText('')
        self.away6.setText('')
        self.away7.setText('')
        self.away8.setText('')
        self.away9.setText('')
        self.away10.setText('')
        self.away11.setText('')
        self.away12.setText('')
        self.away13.setText('')
        self.away14.setText('')
        self.away15.setText('')
        self.away16.setText('')
        self.away17.setText('')
        self.away18.setText('')
        self.away19.setText('')
        
        self.away0.setStyleSheet("font-weight: normal")
        self.away1.setStyleSheet("font-weight: normal")
        self.away2.setStyleSheet("font-weight: normal")
        self.away3.setStyleSheet("font-weight: normal")
        self.away4.setStyleSheet("font-weight: normal")
        self.away5.setStyleSheet("font-weight: normal")
        self.away6.setStyleSheet("font-weight: normal")
        self.away7.setStyleSheet("font-weight: normal")
        self.away8.setStyleSheet("font-weight: normal")
        self.away9.setStyleSheet("font-weight: normal")
        self.away10.setStyleSheet("font-weight: normal")
        self.away11.setStyleSheet("font-weight: normal")
        self.away12.setStyleSheet("font-weight: normal")
        self.away13.setStyleSheet("font-weight: normal")
        self.away14.setStyleSheet("font-weight: normal")
        self.away15.setStyleSheet("font-weight: normal")
        self.away16.setStyleSheet("font-weight: normal")
        self.away17.setStyleSheet("font-weight: normal")
        self.away18.setStyleSheet("font-weight: normal")
        self.away19.setStyleSheet("font-weight: normal")
        
        self.home0.setText('')
        self.home1.setText('')
        self.home2.setText('')
        self.home3.setText('')
        self.home4.setText('')
        self.home5.setText('')
        self.home6.setText('')
        self.home7.setText('')
        self.home8.setText('')
        self.home9.setText('')
        self.home10.setText('')
        self.home11.setText('')
        self.home12.setText('')
        self.home13.setText('')
        self.home14.setText('')
        self.home15.setText('')
        self.home16.setText('')
        self.home17.setText('')
        self.home18.setText('')
        self.home19.setText('')
        
        self.home0.setStyleSheet("font-weight: normal")
        self.home1.setStyleSheet("font-weight: normal")
        self.home2.setStyleSheet("font-weight: normal")
        self.home3.setStyleSheet("font-weight: normal")
        self.home4.setStyleSheet("font-weight: normal")
        self.home5.setStyleSheet("font-weight: normal")
        self.home6.setStyleSheet("font-weight: normal")
        self.home7.setStyleSheet("font-weight: normal")
        self.home8.setStyleSheet("font-weight: normal")
        self.home9.setStyleSheet("font-weight: normal")
        self.home10.setStyleSheet("font-weight: normal")
        self.home11.setStyleSheet("font-weight: normal")
        self.home12.setStyleSheet("font-weight: normal")
        self.home13.setStyleSheet("font-weight: normal")
        self.home14.setStyleSheet("font-weight: normal")
        self.home15.setStyleSheet("font-weight: normal")
        self.home16.setStyleSheet("font-weight: normal")
        self.home17.setStyleSheet("font-weight: normal")
        self.home18.setStyleSheet("font-weight: normal")
        self.home19.setStyleSheet("font-weight: normal")
    
    # for testing
    def showAllText(self):
        self.aScore0.setText('0')
        self.aScore1.setText('1')
        self.aScore2.setText('2')
        self.aScore3.setText('3')
        self.aScore4.setText('4')
        self.aScore5.setText('5')
        self.aScore6.setText('6')
        self.aScore7.setText('7')
        self.aScore8.setText('8')
        self.aScore9.setText('9')
        self.aScore10.setText('10')
        self.aScore11.setText('11')
        self.aScore12.setText('12')
        self.aScore13.setText('13')
        self.aScore14.setText('14')
        self.aScore15.setText('15')
        self.aScore16.setText('16')
        self.aScore17.setText('17')
        self.aScore18.setText('18')
        self.aScore19.setText('19')
        
        self.hScore0.setText('00')
        self.hScore1.setText('11')
        self.hScore2.setText('22')
        self.hScore3.setText('33')
        self.hScore4.setText('44')
        self.hScore5.setText('55')
        self.hScore6.setText('66')
        self.hScore7.setText('77')
        self.hScore8.setText('88')
        self.hScore9.setText('99')
        self.hScore10.setText('10')
        self.hScore11.setText('11')
        self.hScore12.setText('12')
        self.hScore13.setText('13')
        self.hScore14.setText('14')
        self.hScore15.setText('15')
        self.hScore16.setText('16')
        self.hScore17.setText('17')
        self.hScore18.setText('18')
        self.hScore19.setText('19')
        
        self.aScore0.setVisible(True)
        self.aScore1.setVisible(True)
        self.aScore2.setVisible(True)
        self.aScore3.setVisible(True)
        self.aScore4.setVisible(True)
        self.aScore5.setVisible(True)
        self.aScore6.setVisible(True)
        self.aScore7.setVisible(True)
        self.aScore8.setVisible(True)
        self.aScore9.setVisible(True)
        self.aScore10.setVisible(True)
        self.aScore11.setVisible(True)
        self.aScore12.setVisible(True)
        self.aScore13.setVisible(True)
        self.aScore14.setVisible(True)
        self.aScore15.setVisible(True)
        self.aScore16.setVisible(True)
        self.aScore17.setVisible(True)
        self.aScore18.setVisible(True)
        self.aScore19.setVisible(True)
        
        self.hScore0.setVisible(True)
        self.hScore1.setVisible(True)
        self.hScore2.setVisible(True)
        self.hScore3.setVisible(True)
        self.hScore4.setVisible(True)
        self.hScore5.setVisible(True)
        self.hScore6.setVisible(True)
        self.hScore7.setVisible(True)
        self.hScore8.setVisible(True)
        self.hScore9.setVisible(True)
        self.hScore10.setVisible(True)
        self.hScore11.setVisible(True)
        self.hScore12.setVisible(True)
        self.hScore13.setVisible(True)
        self.hScore14.setVisible(True)
        self.hScore15.setVisible(True)
        self.hScore16.setVisible(True)
        self.hScore17.setVisible(True)
        self.hScore18.setVisible(True)
        self.hScore19.setVisible(True)
        
        self.day0.setText('Thu')
        self.day1.setText('Fri')
        self.day2.setText('Sat')
        self.day3.setText('Sun')
        self.day4.setText('Sun')
        self.day5.setText('Sun')
        self.day6.setText('Sun')
        self.day7.setText('Sun')
        self.day8.setText('Sun')
        self.day9.setText('Sun')
        self.day10.setText('Sun')
        self.day11.setText('Sun')
        self.day12.setText('Sun')
        self.day13.setText('Sun')
        self.day14.setText('Sun')
        self.day15.setText('Sun')
        self.day16.setText('Sun')
        self.day17.setText('Sun')
        self.day18.setText('Night')
        self.day19.setText('Mon')
        
        self.ot0.setText('OT')
        self.ot1.setText('OT')
        self.ot2.setText('OT')
        self.ot3.setText('OT')
        self.ot4.setText('OT')
        self.ot5.setText('OT')
        self.ot6.setText('OT')
        self.ot7.setText('OT')
        self.ot8.setText('OT')
        self.ot9.setText('OT')
        self.ot10.setText('OT')
        self.ot11.setText('OT')
        self.ot12.setText('OT')
        self.ot13.setText('OT')
        self.ot14.setText('OT')
        self.ot15.setText('OT')
        self.ot16.setText('OT')
        self.ot17.setText('OT')
        self.ot18.setText('OT')
        self.ot19.setText('OT')
        
        self.result0.setText('C')
        self.result1.setText('X')
        self.result2.setText('X')
        self.result3.setText('C')
        self.result4.setText('X')
        self.result5.setText('C')
        self.result6.setText('X')
        self.result7.setText('C')
        self.result8.setText('X')
        self.result9.setText('C')
        self.result10.setText('X')
        self.result11.setText('C')
        self.result12.setText('X')
        self.result13.setText('C')
        self.result14.setText('X')
        self.result15.setText('C')
        self.result16.setText('X')
        self.result17.setText('C')
        self.result18.setText('X')
        self.result19.setText('C')
        
        self.away0.setText('San Francisco')
        self.away1.setText('Seattle')
        self.away2.setText('Detroit')
        self.away3.setText('Minnesota')
        self.away4.setText('Atlanta')
        self.away5.setText('Tampa Bay')
        self.away6.setText('Dallas')
        self.away7.setText('Philadelphia')
        self.away8.setText('Buffalo')
        self.away9.setText('New York Jets')
        self.away10.setText('Baltimore')
        self.away11.setText('Cleveland')
        self.away12.setText('Tennessee')
        self.away13.setText('Jacksonville')
        self.away14.setText('Denver')
        self.away15.setText('Los Angeles Chargers')
        self.away16.setText('San Francisco')
        self.away17.setText('San Francisco')
        self.away18.setText('San Francisco')
        self.away19.setText('San Francisco')
        
        self.home0.setText('Los Angeles Rams')
        self.home1.setText('Arizona')
        self.home2.setText('Chicago')
        self.home3.setText('Green Bay')
        self.home4.setText('New Orleans')
        self.home5.setText('Carolina')
        self.home6.setText('Washington')
        self.home7.setText('New York Giants')
        self.home8.setText('Miami')
        self.home9.setText('New England')
        self.home10.setText('Pittsburgh')
        self.home11.setText('Cincinnati')
        self.home12.setText('Houston')
        self.home13.setText('Indianapolis')
        self.home14.setText('Las Vegas')
        self.home15.setText('Kansas City')
        self.home16.setText('Los Angeles Rams')
        self.home17.setText('Los Angeles Rams')
        self.home18.setText('Los Angeles Rams')
        self.home19.setText('Los Angeles Chargers')
        
        
app = QApplication(sys.argv)
UIWindow = UI()
app.exec_()


