teams = {
    "ARI": "Arizona",
    "ATL": "Atlanta",
    "BAL": "Baltimore",
    "BUF": "Buffalo",
    "CAR": "Carolina",
    "CHI": "Chicago",
    "CIN": "Cincinnati",
    "CLE": "Cleveland",
    "DAL": "Dallas",
    "DEN": "Denver",
    "DET": "Detroit",
    "GB" : "Green Bay",
    "HOU": "Houston",
    "IND": "Indianapolis",
    "JAX": "Jacksonville",
    "KC" : "Kansas City",
    "LA" : "Los Angeles Rams",
    "LAC": "Los Angeles Chargers",
    "LV" : "Las Vegas",
    "MIA": "Miami",
    "MIN": "Minnesota",
    "NE" : "New England",
    "NO" : "New Orleans", 
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "PHI": "Philadelphia", 
    "PIT": "Pittsburgh",
    "SEA": "Seattle",
    "SF" : "San Francisco",
    "TB" : "Tampa Bay",
    "TEN": "Tennessee",
    "WAS": "Washington"
}

days = ["day0", "day1", "day2", "day3", "day4", "day5", "day6", "day7", "day8", "day9", "day10", "day11", "day12", "day13", "day14", "day15", "day16", "day17", "day18", "day19"]